### ISSUE TITLE
Customer Engagement demo endpoint is dead!

### ISSUE THREAD

**Issue by danders1999** [ibm-cloud-docs/tone-analyzer#91]
I get "404 Not Found: Requested route ('customer-engagement-demo.ng.bluemix.net') does not exist." when I hit the Customer Engagement demo link on the Tone clouddocs page.

I'm trying to demo this in a few hours!

https://customer-engagement-demo.ng.bluemix.net/?cm_mc_uid=54446661241615719244596&cm_mc_sid_50200000=52491461573566447234&cm_mc_sid_52640000=81900841573566447242&_ga=2.198635503.1564644376.1573495467-219326353.1572272476&_gac=1.184062548.1572893830.Cj0KCQiAtf_tBRDtARIsAIbAKe0snb9CC8OzI3Qc6iqwOPjLSP0A3Doyqp-rJDY5hAmDYB9x2lR2H9gaApmcEALw_wcB

**Comment by jdicarl** [comment]
Hello @danders1999 . Thank you for reporting this issue. I apologize for the inconvenience.
I reported the broken link to the dev team and will update this issue when I hear back.

**Comment by jdicarl** [comment]
@danders1999 I'm sorry to report that the demo is deprecated. Here's the info I got from the team:
>Customer engagement demo is deprecated and is no longer being maintained. It looks like the app was deleted as well.
>https://github.com/watson-developer-cloud/customer-engagement-nodejs

I'm going to remove the link from the documentation.

**Comment by jdicarl** [comment]
@danders1999 Good news! The dev team got the customer engagement demo back up and running and will continue supporting it in the future.

I've seen the demo working, but please let us know again if you see that it's down again.
https://customer-engagement-demo.ng.bluemix.net
