### ISSUE TITLE
All available tone ids in docs?

### ISSUE THREAD

**Issue by PergerTech** [ibm-cloud-docs/tone-analyzer#92]
Having issues finding a list of all the standard id_tones responses in the documentation.

**Comment by singhal2** [comment]
Have a similar problem, cannot find a source research for language tones.

**Comment by jeffpk62** [comment]
Do these links answer your questions:

- The general purposes tones are listed here:  https://cloud.ibm.com/docs/tone-analyzer?topic=tone-analyzer-utgpe#tones-tone
- The customer engagement tones are listed here:  https://cloud.ibm.com/docs/tone-analyzer?topic=tone-analyzer-utco#tones-tone-chat

**Comment by singhal2** [comment]
Thank you for your reply. However, I am unable to find documentation in https://cloud.ibm.com/docs/tone-analyzer?topic=tone-analyzer-references regarding Tentative, Analytical, and Confident tone.

**Comment by jeffpk62** [comment]
These tones are listed as possible responses for the "Analyze general tone" method.  For the reference, the possible response tones are merely listed.  The descriptions of the tones are in the IBM Cloud guide links shown previously.   Does that address the question?

The details are typically left to the guide documentation, with the reference serving as a summary of the response values.
