### ISSUE TITLE
IBM Cloud Locations

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/tone-analyzer#94]
I am wondering why when I search IBM Cloud Locations, I will get Satellite, High Availability. What I expect is more around Geographical location map, IBM Locations and Colo. Distance Between them and high level details that cater to better decision making. Is this so difficult. I am working with GSI's that are asking distance between AZs, Data Centers etc. If we cannot publish we can provide, contact us for more details about distances etc. but we must have similar content. Somehow I feel this is more precise information about getting started. I also noticed that connectivity of VSI Gen2, Power VS connectivity should be much simplified. Mounting of logical volumes should be commands that work better for Power VS. Look at such high level requirements and common ennoblement that simplify and provide links to video's that IBM Developed where necessary.

**Comment by jeffpk62** [comment]
@rgentyala I'm sorry.  You should ask your question against a higher-level IBM component.  Issues posted here should be specific to Tone Analyzer.  I'm sorry I can't help, but this is a question that's well beyond Tone.
